[[slaves]]
address = "127.0.0.1"
port = 5020
node_id = 1
enabled = true

[protocol_interface_settings]
baudrate = 9600
start_bits = 1
data_bits = 8
stop_bits = 1
parity = "none"
crc_order = "low_high"
sbms_address = 1
invalid_reg_flag = 55536
local_ip_address = "192.168.1.60"
subnet_mask = "255.255.255.0"
local_gateway = "192.168.1.1"
port = 5020

[global]
polling_interval_ms = 2000
timeout_ms = 500
device_name = "hidesun_sbms"

[registers.battery_config]
start_id = 8000
read_count = 37
description = "电池组配置信息"
[[registers.battery_config.items]]
id = 8000
name = "reserved_1"
words = 1
type = "uint16"
description = "保留"

[[registers.battery_config.items]]
id = 8001
name = "reserved_2"
words = 1
type = "uint16"
description = "保留"

[[registers.battery_config.items]]
id = 8002
name = "reserved_3"
words = 1
type = "uint16"
description = "预留"

[[registers.battery_config.items]]
id = 8003
name = "battery_pack_nums"
words = 1
type = "uint16"
description = "电池组数，1-4，缺省为4"
min = 1
max = 4
default = 4

[[registers.battery_config.items]]
id = 8004
name = "battery_pack_1_cells"
words = 1
type = "uint16"
description = "第1组电池节数，数据需要校验，每组电芯不超过250节"
min = 0
max = 250

[[registers.battery_config.items]]
id = 8005
name = "battery_pack_2_cells"
words = 1
type = "uint16"
description = "第2组电池节数，数据需要校验，每组电芯不超过250节"
min = 0
max = 250

[[registers.battery_config.items]]
id = 8006
name = "battery_pack_3_cells"
words = 1
type = "uint16"
description = "第3组电池节数，数据需要校验，每组电芯不超过250节"
min = 0
max = 250

[[registers.battery_config.items]]
id = 8007
name = "battery_pack_4_cells"
words = 1
type = "uint16"
description = "第4组电池节数，数据需要校验，每组电芯不超过250节"
min = 0
max = 250

[[registers.battery_config.items]]
id = 8008
name = "battery_pack_1_type"
words = 1
type = "uint16"
description = "第1组电池类型，0: 2V, 1: 6V, 2: 12V"
default = 2
allowed_values = [ 0, 1, 2,]

[[registers.battery_config.items]]
id = 8009
name = "battery_pack_2_type"
words = 1
type = "uint16"
description = "第2组电池类型，0: 2V, 1: 6V, 2: 12V"
default = 2
allowed_values = [ 0, 1, 2,]

[[registers.battery_config.items]]
id = 8010
name = "battery_pack_3_type"
words = 1
type = "uint16"
description = "第3组电池类型，0: 2V, 1: 6V, 2: 12V"
default = 2
allowed_values = [ 0, 1, 2,]

[[registers.battery_config.items]]
id = 8011
name = "battery_pack_4_type"
words = 1
type = "uint16"
description = "第4组电池类型，0: 2V, 1: 6V, 2: 12V"
default = 2
allowed_values = [ 0, 1, 2,]

[[registers.battery_config.items]]
id = 8012
name = "battery_pack_1_capacity"
words = 1
type = "uint16"
description = "第1组电池安时数，7~5000（AH）"
min = 7
max = 5000

[[registers.battery_config.items]]
id = 8013
name = "battery_pack_2_capacity"
words = 1
type = "uint16"
description = "第2组电池安时数，7~5000（AH）"
min = 7
max = 5000

[[registers.battery_config.items]]
id = 8014
name = "battery_pack_3_capacity"
words = 1
type = "uint16"
description = "第3组电池安时数，7~5000（AH）"
min = 7
max = 5000

[[registers.battery_config.items]]
id = 8015
name = "battery_pack_4_capacity"
words = 1
type = "uint16"
description = "第4组电池安时数，7~5000（AH）"
min = 7
max = 5000

[[registers.battery_config.items]]
id = 8016
name = "reserved_4"
words = 1
type = "uint16"
description = "预留"

[[registers.battery_config.items]]
id = 8017
name = "reserved_5"
words = 1
type = "uint16"
description = "预留"

[[registers.battery_config.items]]
id = 8018
name = "reserved_6"
words = 1
type = "uint16"
description = "预留"

[[registers.battery_config.items]]
id = 8019
name = "reserved_7"
words = 1
type = "uint16"
description = "预留"

[[registers.battery_config.items]]
id = 8020
name = "reserved_8"
words = 3
type = "reserved"
description = "预留（3个字）"

[[registers.battery_config.items]]
id = 8023
name = "mac_address"
words = 3
type = "mac"
description = "6个字节构成的 MAC 地址"
parse_func = "parseRegMAC"

[[registers.battery_config.items]]
id = 8026
name = "ip_address"
words = 2
type = "ipv4"
description = "网络 IP 地址"
default = "192.168.0.20"
parse_func = "parseRegIPv4"

[[registers.battery_config.items]]
id = 8028
name = "gateway"
words = 2
type = "ipv4"
description = "网关 IP 地址"
default = "192.168.0.1"
parse_func = "parseRegIPv4"

[[registers.battery_config.items]]
id = 8030
name = "subnet_mask"
words = 2
type = "ipv4"
description = "子网掩码"
default = "255.255.255.0"
parse_func = "parseRegIPv4"

[[registers.battery_config.items]]
id = 8032
name = "dns"
words = 2
type = "ipv4"
description = "网络 DNS"
parse_func = "parseRegIPv4"

[[registers.battery_config.items]]
id = 8034
name = "socket_port"
words = 1
type = "uint16"
description = "Socket 目标端口号"
default = 502

[[registers.battery_config.items]]
id = 8035
name = "target_ip_address"
words = 2
type = "ipv4"
description = "目标服务器 IP 地址"
default = "192.168.0.100"
parse_func = "parseRegIPv4"

[registers.system_time]
start_id = 8300
read_count = 7
description = "系统时间"
[[registers.system_time.items]]
id = 8300
name = "year"
words = 2
type = "uint16"
description = "年"
min = 2000

[[registers.system_time.items]]
id = 8302
name = "month"
words = 1
type = "uint16"
description = "月"
min = 1
max = 12

[[registers.system_time.items]]
id = 8303
name = "day"
words = 1
type = "uint16"
description = "日"
min = 1
max = 31

[[registers.system_time.items]]
id = 8304
name = "hour"
words = 1
type = "uint16"
description = "时"
min = 0
max = 23

[[registers.system_time.items]]
id = 8305
name = "minute"
words = 1
type = "uint16"
description = "分"
min = 0
max = 59

[[registers.system_time.items]]
id = 8306
name = "second"
words = 1
type = "uint16"
description = "秒"
min = 0
max = 59

